### ISSUE TITLE
Creating a bag from a remote file manifest raises an exception

### ISSUE THREAD

**Issue by NickolausDS** [ini-bdds/bdbag#15]
When creating a bag with the following command:

    $ bdbag bag/ --remote-file-manifest manifest.json

An error is raised:

    RuntimeError: Expected the same number of files for each checksum

Details about the above command:
* Run with Bagit version bagit==1.6.2
* Run with BDBag version bdbag==1.1.1
* `bag/` in the command above is an empty directory
* `manifest.json` corresponds to the [example in the docs](https://github.com/ini-bdds/bdbag/blob/master/doc/config.md#remote-file-manifest)

This didn't seem to happen on previous versions. Before, it allowed me to create an 'empty' bdbag with a fetch file that could be used to pull down the remote files and validate them.

**Comment by mikedarcy** [comment]
Unfortunately, this is an issue with `bagit-1.6.x` and some new error checking logic which basically is prohibiting the bagging of an empty directory.  I can reproduce this with just `bagit ./bag/` on an empty directory.  This worked in `bagit-1.5.4` and I think needs to continue to work.  There is a pretty easy one line fix for this in `bagit.py` so I will file a PR with bagit and see what they have to say.

**Comment by mikedarcy** [comment]
File a PR for `bagit`: https://github.com/LibraryOfCongress/bagit-python/pull/100
