### ISSUE TITLE
Add FTP fetch handler

### ISSUE THREAD

**Issue by mikedarcy** [ini-bdds/bdbag#3]

**Comment by edeutsch** [comment]
Hi Mike, would it be possible to prioritize this? We would really like to have ftp URLs in fetch.txt. I thought this worked, but just discovered that it doesn't.

**Comment by mikedarcy** [comment]
I'm working on implementing this now.  No ETA yet.

**Comment by mikedarcy** [comment]
Implemented with unit test passing as of 304f04c.

Closing issue.  Please report any bugs in a separate issue.
