### ISSUE TITLE
Add mechanism to avoid creation of $HOME/.bdbag

### ISSUE THREAD

**Issue by edeutsch** [ini-bdds/bdbag#7]
I am trying to run minid and bdbag from a captive account that doesn't have a proper writable home directory for security reasons.
When I run minid, I specify this:
minid --config /net/db/projects/BDDS/TPP/.minid/minid-config.cfg
and it is totally happy.
However, when I run bdbag with this:
bdbag --config-file /net/db/projects/BDDS/TPP/.bdbag/bdbag.json
it still insists on wanting to create a $HOME/.bdbag directory. But for security reasons, it is not allowed to do this. This is apparently in order to create a keychain.json file.
Would you adjust the code so that bdbag can be run without wanting to create a directory in the caller's home directory? This may not always be possible (like in one of my test cases here).

**Comment by mikedarcy** [comment]
Made some changes to address this in commit a6d25c92c94e2318a72df4a37d3772a752bf1f75.
