### ISSUE TITLE
Installation via pip ?

### ISSUE THREAD

**Issue by tseemann** [ini-bdds/bdbag#8]
It would be helpful for packaging if you could support pip:

```
pip install https://github.com/ini-bdds/bdbag
```

**Comment by mikedarcy** [comment]
Will look into this. Thanks!

**Comment by mikedarcy** [comment]
We have some custom dependencies that aren't on PyPi which is why the basic pip install command doesn't work.

However, I was able to get it working using the following command:

```sh
pip install --process-dependency-links --allow-all-external http://github.com/ini-bdds/bdbag/archive/master.zip
```
Let me know if it works for you and if so I will update the README.md and close this out.

**Comment by stain** [comment]
See #10 which would simplify pip release - perhaps we can also get the bagit-profiles-validator released officially for pip?

**Comment by stain** [comment]
There is also a newer `bagit_profile=1.1.1` (note the underscore) - but I only had a quick try with it - something in how bdbag call it is broken as some of the tests fail.  So perhaps need to update those calls.

**Comment by mikedarcy** [comment]
The changes in PR https://github.com/ini-bdds/bdbag/pull/13 should take care of this.

**Comment by stain** [comment]
#13 works great, tested with a fresh  virtualenv!  

Would you be able to merge this and perhaps roll a release towards pypi? We would like to use this from [commonworkflowlanguage/cwltool](https://github.com/common-workflow-language/cwltool)

**Comment by mikedarcy** [comment]
Working on it now.  Will update bagit dependency to latest 1.6.2 and get pypi going.

**Comment by mikedarcy** [comment]
Release [1.1.1](https://github.com/ini-bdds/bdbag/releases/tag/v1.1.1) has been tagged and uploaded to PyPi.  

One can now `pip install bdbag`.
